- name: /etc/nixos/configuration.nix
  template:
    src: "{{ item }}"
    dest: "/etc/nixos/{{ item }}"
    mode: "644"
    owner: root
    group: root
  become: true
  notify: rebuild nix
  loop:
    - configuration.nix
    - hardware-configuration.nix
    - cachix.nix
    - flake.nix


    #- name: samba secret
    #  template:
    #    src: "smb-secrets"
    #    dest: "/etc/nixos/smb-secrets"
    #    mode: "600"
    #  become: true
    #
    #- name: backup secrets
    #  template:
    #    src: "backup-secrets"
    #    dest: "/etc/nixos/backup-secrets"
    #    mode: "600"
    #  become: true
