- name: install haproxy
  apt:
    name: haproxy
    state: present

- name: add haproxy.cfg
  template:
    src: templates/haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg
  notify: restart haproxy

- name: Allow http and https through firewall
  ufw:
    rule: allow
    port: "{{ item }}"
  with_items:
    - 80
    - 443
