- hosts: bab-website
  user: root
  become: yes
  roles:
    - vm-networking
    - hostname
    - apt
    - unattended-upgrades
    - sshd
    - firewall
    - certificates
    - backup-client
    - bab-website
    - letsencrypt-nginx
    - munin-node
    - icinga-client
