- hosts: debugproxy
  user: root
  become: yes
  roles:
    - vm-networking
    - hostname
    #- apt-bookworm
    - python/python37
    - unattended-upgrades
    - firewall
    - certificates
    #- munin-node
    #- icinga-client
    #- icinga-plugins
    - debugproxy
