- hosts: monitoring
  user: root
  become: yes
  roles:
    - vm-networking
    - apt
    - unattended-upgrades
    - sshd
    - hostname
    - firewall
    - certificates
    - backup-client
    - letsencrypt-apache
    - munin-master
    - icinga-client
