- hosts: owncloud
  user: root
  become: yes
  roles:
    - vm-networking
    - hostname
    - apt
    - unattended-upgrades
    - sshd
    - certificates
    - backup-client
    - icinga-client
    - owncloud
    - letsencrypt-apache
    - munin-node
    - unattended-upgrades
