- name: Create ~/.profiles directory
  file:
    path: /home/{{ username }}/.profiles
    state: directory
    group: "{{ usergroup }}"
    owner: "{{ username }}"

- name: ~/.bashrc
  template:
    src: bashrc
    dest: "/home/{{ username }}/.bashrc"
    group: "{{ usergroup }}"
    owner: "{{ username }}"

- name: ~/.bash_profile
  template:
    src: bash_profile
    dest: "/home/{{ username }}/.bash_profile"
    group: "{{ usergroup }}"
    owner: "{{ username }}"

- name: remove ~/.profile
  file:
    state: absent
    path: "/home/{{ username }}/.profile"
