- name: /home/tarn/.muttrc
  template:
    src: "muttrc"
    dest: "/home/tarn/.muttrc"
    owner: tarn

- name: ensure directories
  file:
    dest: "{{ item }}"
    state: directory
    owner: tarn
  with_items:
    - /home/tarn/.mutt
    - /home/tarn/.config
    - /home/tarn/.config/vdirsyncer
    - /home/tarn/.config/khard
    - /home/tarn/.config/khal

- name: copy mutt configuration files
  template:
    src: "{{ item }}"
    dest: "/home/tarn/.mutt/{{ item }}"
    owner: tarn
  with_items:
    - colours.muttrc
    - debugproxy.muttrc
    - mailcap
    - tarnbarford.muttrc
    - offlineimap-pass.py

- name: copy vdirsyncer configuration file
  template:
    src: "vdirsyncer.conf"
    dest: "/home/tarn/.config/vdirsyncer/config"
    owner: tarn

- name: copy khal configuration file
  template:
    src: "khal.conf"
    dest: "/home/tarn/.config/khal/config"
    owner: tarn

- name: copy msmtp configuration file
  template:
    src: "msmtprc"
    dest: "/home/tarn/.msmtprc"
    owner: tarn

- name: copy offlineimap configuration file
  template:
    src: "offlineimaprc"
    dest: "/home/tarn/.offlineimaprc"
    owner: tarn

- name: copy khard configuration file
  template:
    src: "khard.conf"
    dest: "/home/tarn/.config/khard/khard.conf"
    owner: tarn

- name: copy urlview configuration file
  template:
    src: "urlview"
    dest: "/home/{{ username }}/.urlview"
    owner: "{{ username }}"
