- name: /home/tarn/.muttrc
  template:
    src: "muttrc"
    dest: "/home/tarn/.muttrc"
    owner: tarn

- name: ensure directories
  file:
    dest: "{{ item }}"
    state: directory
    owner: tarn
  with_items:
    - /home/tarn/.config
    - /home/tarn/.config/vdirsyncer
    - /home/tarn/.config/khard

- name: copy mutt configuration files
  template:
    src: "{{ item }}"
    dest: "/home/tarn/.mutt/{{ item }}"
    owner: tarn
  with_items:
    - colours.muttrc
    - debugproxy.muttrc
    - mailcap
    - tarnbarford.muttrc

- name: copy vdirsyncer configuration file
  template:
    src: "vdirsyncer.conf"
    dest: "/home/tarn/.config/vdirsyncer/config"
    owner: tarn

- name: copy khard configuration file
  template:
    src: "khard.conf"
    dest: "/home/tarn/.config/khard/khard.conf"
    owner: tarn

- name: copy urlview configuration file
  template:
    src: "urlview"
    dest: "/home/{{ username }}/.urlview"
    owner: "{{ username }}"
