- name: Install packages
  apt:
    name: [
      'vim',
      'git',
      'curl',
      'wget',
      'tmux',
      'net-tools',
      'silversearcher-ag',
      'locales',
      'python3-venv'
    ]
    state: present
    update_cache: yes

- name: Clone dotfiles repository
  git:
    repo: git@github.com:tarnacious/dotfiles.git
    dest: /home/tarn/.dotfiles
    version: master
    accept_hostkey: True
    force: yes
  become: yes
  become_user: tarn

- name: Create symbolic links to dotfiles
  file:
    src: "/home/tarn/.dotfiles/.{{ item }}"
    dest: "/home/tarn/.{{ item }}"
    state: link
  with_items:
    - vimrc
    - gitconfig
    - gitignore.global
    - bash_profile
#    - bashrc
    - tmux.conf
    - msmtprc
    - offlineimaprc
    - muttrc

- name: Create ~/.vim directory
  file:
    path: /home/tarn/.vim
    state: directory
    group: tarn
    owner: tarn
    recurse: yes

- name: Create ~/.vim/autoload directory
  file:
    path: /home/tarn/.vim/autoload
    state: directory
    group: tarn
    owner: tarn
    recurse: yes

- name: Download vim plugin manager
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: /home/tarn/.vim/autoload/plug.vim
    checksum: sha256:49e4b25f789f10639155863b17dabdccb9d59b0d12ced0299c40a81533660bf3

- name: Ensure a locale exists
  locale_gen:
    name: en_US.UTF-8
    state: present
