- name: Install packages
  apt:
    name: [
      'vim',
      'git',
      'curl',
      'wget',
      'unzip',
      'tmux',
      'net-tools',
      'silversearcher-ag',
      'locales',
      'python3-venv',
      'gpgconf',
      'htop',
      'iftop',
      'dnsutils',
      'build-essential',
      'postgresql-client'
    ]
    state: present
    update_cache: yes

- name: Create ~/bin
  file:
    path: /home/{{ username }}/bin
    state: directory
    group: "{{ username }}"
    owner: "{{ username }}"
    recurse: yes

- name: Create ~/bin files
  template:
    src: templates/{{ item }}
    dest: /home/{{ username }}/bin/{{ item }}
    mode: 0755
  become: yes
  become_user: "{{ username }}"
  with_items:
    - decrypt
    - encrypt
