- name: reload supervisor
  action: service name=supervisor state=restarted

- name: restart nginx
  action: service name=nginx state=restarted

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes



