- name: 'Check mandatory variables are defined'
  assert:
    that:
      - hostname is defined

- name: set /etc/network/interfaces
  template:
    src: templates/interfaces
    dest: /etc/network/interfaces

- name: set /etc/resolv.conf
  template:
    src: templates/resolv.conf
    dest: /etc/resolv.conf
