- name: create certificate directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /home/tarn/.pki/CA/
    - /home/tarn/.pki/libvirt/
    - /home/tarn/.pki/libvirt/private

- name: copy libvirt ca certificate
  copy:
    src: "libvirt-ca/ca.crt"
    dest: "/home/tarn/.pki/libvirt/cacert.pem"

- name: copy libvirt client private key
  copy:
    src: "libvirt-ca/client.key"
    dest: "/home/tarn/.pki/libvirt/clientkey.pem"

- name: copy libvirt client public key
  copy:
    src: "libvirt-ca/client.crt"
    dest: "/home/tarn/.pki/libvirt/clientcert.pem"
