all:
  vars:
    ansible_user: tarn
    ansible_python_interpreter: /usr/bin/env python3
  hosts:
    thinkpad:
      ansible_user: tarn
      ansible_host: localhost
    dellxps:
      ansible_user: tarn
      ansible_host: localhost
    nas:
      ansible_user: pi
      ansible_host: nas.tarnbarford.net
    hypervisor:
      ansible_host: !vault |
        $ANSIBLE_VAULT;1.1;AES256
        65396638623437653232343938306261643264646162386532356664383061666363336564323730
        3165313438313264633933663361653837343733373736340a323565343164396263343131616232
        65313436366664343565646533383265343332646164346231356535393831323331646662313333
        3865353133316531640a336532666632313964366564373431666662333935323566653732343136
        6135
    monitoring:
      ansible_host: 192.168.122.7
      ansible_ssh_common_args: "-o ProxyCommand='ssh -q -W %h:%p tarn@hypervisor.tarnbarford.net'"
    load-balancer:
      ansible_host: 192.168.122.8
      ansible_ssh_common_args: "-o ProxyCommand='ssh -q -W %h:%p tarn@hypervisor.tarnbarford.net'"
    tarnbarford:
      ansible_host: 192.168.122.9
      ansible_ssh_common_args: "-o ProxyCommand='ssh -q -W %h:%p tarn@hypervisor.tarnbarford.net'"
    bab-website:
      ansible_host: 192.168.122.10
      ansible_ssh_common_args: "-o ProxyCommand='ssh -q -W %h:%p tarn@hypervisor.tarnbarford.net'"
    owncloud:
      ansible_host: 192.168.122.11
      ansible_ssh_common_args: "-o ProxyCommand='ssh -q -W %h:%p tarn@hypervisor.tarnbarford.net'"
    mail-server:
      ansible_host: 192.168.122.12
      ansible_ssh_common_args: "-o ProxyCommand='ssh -q -W %h:%p tarn@hypervisor.tarnbarford.net'"
    icinga2:
      ansible_host: 192.168.122.13
      ansible_ssh_common_args: "-o ProxyCommand='ssh -q -W %h:%p tarn@hypervisor.tarnbarford.net'"
    icinga:
      ansible_host: 192.168.122.14
      ansible_ssh_common_args: "-o ProxyCommand='ssh -q -W %h:%p tarn@hypervisor.tarnbarford.net'"
    ns1:
      ansible_host: 192.168.122.16
      ansible_ssh_common_args: "-o ProxyCommand='ssh -q -W %h:%p tarn@hypervisor.tarnbarford.net'"
    debugproxy:
      ansible_user: tarn
      ansible_host: 192.168.122.17
      ansible_ssh_common_args: "-o ProxyCommand='ssh -q -W %h:%p tarn@hypervisor.tarnbarford.net'"
    dns:
      ansible_user: tarn
      ansible_host: 192.168.122.20 
      ansible_ssh_common_args: "-o ProxyCommand='ssh -q -W %h:%p tarn@hypervisor.tarnbarford.net'"
    bacula:
      ansible_user: tarn
      ansible_host: 192.168.122.21
      ansible_ssh_common_args: "-o ProxyCommand='ssh -q -W %h:%p tarn@hypervisor.tarnbarford.net'"
    postgres:
      ansible_user: tarn
      ansible_host: 192.168.122.22 
      ansible_ssh_common_args: "-o ProxyCommand='ssh -q -W %h:%p tarn@hypervisor.tarnbarford.net'"
    trains:
      ansible_user: tarn
      ansible_host: 192.168.122.24
      ansible_ssh_common_args: "-o ProxyCommand='ssh -q -W %h:%p tarn@hypervisor.tarnbarford.net'"
    snapper:
      ansible_user: tarn
      ansible_host: 192.168.122.34
      ansible_ssh_common_args: "-o ProxyCommand='ssh -q -W %h:%p tarn@hypervisor.tarnbarford.net'"
    australia:
      ansible_host: "170.64.129.0"
    robot:
      ansible_host: 192.168.0.161
