- name: install packages
  apt:
    name: ['scdaemon', 'gpg', 'gpgconf', 'pcscd']
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: install nitrokey udev rules
  template:
    src: nitrokey.rules
    dest: /etc/udev/rules.d/41-nitrokey.rules
  when: ansible_os_family == "Debian"

- name: ~/.profiles/gpgssh_profile
  template:
    src: gpgssh_profile
    dest: "/home/{{ username }}/.profiles/gpgssh_profile"
    group: "{{ usergroup }}"
    owner: "{{ username }}"

- name: ensure .gnupg directory
  file:
    dest: "/home/{{ username }}/.gnupg"
    state: directory
    group: "{{ usergroup }}"
    owner: "{{ username }}"
    mode: 0700

- name: ~/.gnupg/gpg.conf
  template:
    src: gpg.conf
    dest: "/home/{{ username }}/.gnupg/gpg.conf"
    group: "{{ usergroup }}"
    owner: "{{ username }}"

- name: ~/.gnupg/gpg-agent.conf
  template:
    src: gpg-agent.conf
    dest: "/home/{{ username }}/.gnupg/gpg-agent.conf"
    group: "{{ usergroup }}"
    owner: "{{ username }}"
