- name: Install list of packages
  apt:
    name: [
      'ufw',
      'htop'
    ]
    state: present
    update_cache: yes


- name: Allow SSH access
  ufw:
    rule: allow
    port: '22'

- name: set default routed policy to accept
  ufw:
    policy: allow
    direction: routed

- name: add before.rules
  template:
    src: templates/ufw/before.rules
    dest: /etc/ufw/before.rules
  notify: reload ufw

- name: Enable UFW
  ufw:
    state: enabled
    policy: reject

- name: add /etc/network/interfaces
  template:
    src: templates/interfaces
    dest: /etc/network/interfaces
  notify: restart networking

- name: add /var/kvm/images directory
  file:
    path: /var/kvm/images
    state: directory
    mode: '0755'

- sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

- sysctl:
    name: net.ipv4.conf.enp2s0.send_redirects
    value: '0'
    sysctl_set: yes
    state: present
    reload: yes

- sysctl:
    name: net.ipv6.conf.all.forwarding
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
