- name: set hostname to brainsome
  hostname:
    name: "brainsome"

- apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present

- apt_repository:
    repo: deb https://dl.yarnpkg.com/debian/ stable main
    state: present

- name: Install packages
  apt:
    name: [
      'nodejs',
      'npm',
      'yarn',
      'build-essential',
      'libssl-dev',
      'libreadline-dev',
      'libpq-dev',
      'tzdata',
      'imagemagick',
      'libfontconfig1',
      'libfreetype6',
      'netcat',
      'ssh',
      'curl',
      'redis-tools',
      'memcached',
      'libjpeg-turbo-progs',
      'pngcrush',
      'libicu-dev',
      'pandoc',
      'git',
      'libicu-dev',
      'chromium',
      'postgresql-client-11',
      'rsync',
      'python3-venv',
      'python3-dev',
      'libtag1-dev',
      #'chromedriver',
      ]
    state: present
    update_cache: yes

- name: Clone piqd repository
  git:
    repo: git@github.com:brainsome-de/piqd.git
    dest: /home/tarn/piqd
    version: testing
    accept_hostkey: True
    force: no
    update: no
  become: no
  become_user: tarn

- name: Clone torial repository
  git:
    repo: git@github.com:brainsome-de/torial.git
    dest: /home/tarn/torial
    version: testing
    accept_hostkey: True
    force: no
    update: no
  become: yes
  become_user: tarn

- name: Clone infrastructure repository
  git:
    repo: git@github.com:brainsome-de/infrastructure.git
    dest: /home/tarn/infrastructure
    version: master
    accept_hostkey: True
    force: no
    update: no
  become: yes
  become_user: tarn

- name: Clone puppet repository
  git:
    repo: git@github.com:brainsome-de/puppet5-master.git
    dest: /home/tarn/puppet
    version: production
    accept_hostkey: True
    force: no
    update: no
  become: yes
  become_user: tarn

- name: Download chromedriver
  unarchive:
    src: https://chromedriver.storage.googleapis.com/80.0.3987.106/chromedriver_linux64.zip
    dest: /usr/local/bin
    remote_src: yes

- name: Download phrase app binary
  get_url:
    url: https://github.com/phrase/phraseapp-client/releases/download/1.16.1/phraseapp_linux_amd64
    dest: /usr/local/bin/phrase-app
    mode: '0755'

- name: brainsome ~/.ssh/config 
  template:
    src: ssh_config
    dest: /home/tarn/.ssh/config
    owner: tarn
    group: tarn
