- name: Install packages
  apt:
    name: [
      'certbot',
      'python-certbot-nginx',
      'mariadb-server',
      'git',
      'nginx',
      'php-fpm',
      'php-mysql',
      'nginx-extras'
    ]
    state: latest
    update_cache: yes

- name: Add the user 'bab'
  user:
    name: bab

- name: Start PHP-FPM
  service:
    name: php7.3-fpm
    state: started
    enabled: True

- name: Configure nginx
  copy:
    src: templates/nginx.conf
    dest: /etc/nginx/sites-enabled/default
  notify: restart nginx

- name: Check if wp-cli exists
  stat: path="/usr/bin/wp"
  register: wpcli_exist

- name: Download wp-cli
  get_url:
    url: 'https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar'
    dest: "/usr/bin/wp"
    mode: '0755'
  when: not wpcli_exist.stat.exists
