- name: add create vm script
  copy:
    src: templates/build_vm
    dest: /usr/bin/build_vm
    mode: '0744'

- name: add create domain script
  copy:
    src: templates/create_domain
    dest: /usr/bin/create_domain
    mode: '0744'
