- name: Install list of packages for sendmail
  apt:
    name: [
      "sendmail",
      "mailutils",
      "sendmail-bin",
      "sasl2-bin"
    ]
    state: present
    update_cache: yes

- name: create auth info directory
  file:
    name: /etc/mail/authinfo/
    state: directory
    mode: "750"

- name: copy authentication file
  template:
    src: templates/authinfo
    dest: /etc/mail/authinfo/authinfo
    mode: "0750"

- name: copy generics table
  template:
    src: templates/genericstable
    dest: /etc/mail/genericstable
    group: smmsp
    mode: "0750"

- name: copy generic-domains
  template:
    src: templates/generics-domains
    dest: /etc/mail/generics-domains
    group: smmsp
    mode: "0750"

- name: copy sendmail config
  template:
    src: templates/sendmail.mc
    dest: /etc/mail/sendmail.mc
    group: smmsp
  notify: restart sendmail

- name: generate auth info db
  shell: makemap hash authinfo < authinfo
  args:
    chdir: /etc/mail/authinfo/

- name: rebuild sendmail
  shell: make
  args:
    chdir: /etc/mail
