- name: Download and extract golang
  unarchive:
    src: https://dl.google.com/go/go1.14.4.linux-amd64.tar.gz
    dest: /usr/local/
    remote_src: yes

- name: Ensure ~/.profiles
  file:
    path: /home/tarn/.profiles
    state: directory

- name: Ensure ~/.go
  file:
    path: /home/tarn/.go
    state: directory

- name: Go bash profile in ~/.profiles
  template:
    src: templates/go_rc
    dest: /home/tarn/.profiles/go_rc
