- name: Install list of packages
  apt:
    name: [
      "bareos",
      "postgresql",
      "cifs-utils"
    ] 
    state: present
    update_cache: yes

- name: delete default configurations
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/bareos/bareos-dir.d/director/bareos-dir.conf
    - /etc/bareos/bareos-dir.d/job/backup-bareos-fd.conf
    - /etc/bareos/bareos-dir.d/job/BackupCatalog.conf
    - /etc/bareos/bareos-dir.d/job/RestoreFiles.conf
    - /etc/bareos/bareos-dir.d/jobdefs/DefaultJob.conf
    - /etc/bareos/bareos-dir.d/pools/DefaultJob.conf
    - /etc/bareos/bareos-dir.d/pools/Differential.conf
    - /etc/bareos/bareos-dir.d/pools/Full.conf
    - /etc/bareos/bareos-dir.d/pools/Incremental.conf
    - /etc/bareos/bareos-dir.d/schedule/WeeklyCycleAfterBackup.conf
    - /etc/bareos/bareos-dir.d/schedule/WeeklyCycle.conf
    - /etc/bareos/bareos-dir.d/console/bareos-mon.conf
    - /etc/bareos/bareos-dir.d/client/bareos-fd.conf
    - /etc/bareos/bareos-dir.d/catalog/MyCatalog.conf
    - /etc/bareos/bareos-dir.d/storage/File.conf
    - /etc/bareos/bareos-dir.d/messages/Daemon.conf
    - /etc/bareos/bareos-dir.d/messages/Standard.conf
    - /etc/bareos/bareos-sd.d/devices/FileStorage.conf
  notify: restart bareos-dir

- name: copy bareos dir
  template:
    src: "templates/bareos-dir.d/{{ item }}"
    dest: /etc/bareos/bareos-dir.d/{{ item }}
  with_items:
    - storage/storages.conf
    - job/jobs.conf
    - schedule/schedules.conf
    - storage/storages.conf
    - pool/pools.conf
    - fileset/filesets.conf
    - jobdefs/jobdefs.conf
    - client/clients.conf
    - director/director.conf
    - catalog/catalogs.conf
    - messages/messages.conf
  notify: restart bareos-dir

- name: copy bareos fd
  template:
    src: "templates/bareos-fd.d/{{ item }}"
    dest: /etc/bareos/bareos-fd.d/{{ item }}
  with_items:
    - director/bareos-dir.conf
    - client/myself.conf
  notify: restart bareos-fd

- name: copy bconsole configuration
  template:
    src: "templates/bconsole.conf"
    dest: /etc/bareos/bconsole.conf

- name: storage director configurations
  template:
    src: "templates/bareos-sd.d/{{ item }}"
    dest: /etc/bareos/bareos-sd.d/{{ item }}
  with_items:
    - director/bareos-dir.conf
    - device/devices.conf
    - storage/bareos-sd.conf
  notify: restart bareos-sd

- name: Allow access to port 9103 for bacula storage
  ufw:
    rule: allow
    port: "9103"
    from_ip: "{{ hypervisor_ipv6_subnet }}"

- name: copy backup credentials
  template:
    src: templates/backup-credentials
    dest: /etc/backup-credentials
    mode: "0600"
  notify: remount all

- name: create mount dir /mnt/backup
  file:
    dest: /mnt/backup
    state: directory

- name: fstab with network drive
  template:
    src: templates/fstab
    dest: /etc/fstab
  notify: remount all
