- name: Install packages
  apt:
    name: ['git']
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Configure config
  template:
    src: templates/config
    dest: /home/{{ username }}/.gitconfig
    mode: 0600
  become: yes
  become_user: "{{ username }}"

- name: Configure ignore
  template:
    src: templates/ignore
    dest: /home/{{ username }}/.gitignore.global
    mode: 0600
  become: yes
  become_user: "{{ username }}"

- name: ~/.profiles/git_profile
  template:
    src: git_profile
    dest: "/home/{{ username }}/.profiles/git_profile"
    group: "{{ usergroup }}"
    owner: "{{ username }}"
