- name: install wireguard packages
  apt:
    name: [
      "wireguard",
    ]
    state: present
    update_cache: yes

- name: set /etc/wireguard/wg0.conf
  template:
    src: templates/wg0.conf
    dest: /etc/wireguard/wg0.conf

- name: create /etc/wireguard/scripts directory
  file:
    path: /etc/wireguard/scripts
    state: directory

- name: set /etc/wireguard/scripts/add-nat-routing.sh
  template:
    src: templates/add-nat-routing.sh
    dest: /etc/wireguard/scripts/add-nat-routing.sh
    mode: a+x

- name: set /etc/wireguard/scripts/del-nat-routing.sh
  template:
    src: templates/del-nat-routing.sh
    dest: /etc/wireguard/scripts/del-nat-routing.sh
    mode: a+x

- name: allow wireguard udp port
  ufw:
    rule: allow
    proto: udp
    port: "51194"

- sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

- sysctl:
    name: net.ipv6.conf.all.forwarding
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

- name: ensure wireguard service started
  service:
    name: wg-quick@wg0
    state: started
    enabled: false
