- name: add buster backports repository
  template:
    src: templates/buster-backports.list
    dest: /etc/apt/sources.list.d/buster-backports.list

- name: install wireguard packages
  apt:
    name: [
      "wireguard",
      "wireguard-dkms",
      "resolvconf"
    ]
    state: present
    update_cache: yes

- name: set /etc/network/interfaces
  template:
    src: templates/interfaces
    dest: /etc/network/interfaces

- name: set /etc/wireguard/wg0.conf
  template:
    src: templates/wg0.conf
    dest: /etc/wireguard/wg0.conf

- name: ensure wireguard service started
  service:
    name: wg-quick@wg0
    state: started
    enabled: true

- name: allow wireguard udp port
  ufw:
    rule: allow
    proto: udp
    port: "{{ wg0_port }}"

- sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

- sysctl:
    name: net.ipv6.conf.all.forwarding
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
