- name: set /etc/apt/preferences.d/limit_unstable
  template:
    src: templates/limit_unstable
    dest: /etc/apt/preferences.d/limit_unstable

- name: set /etc/apt/sources.list.d/unstable-wireguard.list
  template:
    src: templates/unstable-wireguard.list
    dest: /etc/apt/sources.list.d/unstable-wireguard.list

- name: install wireguard packages
  apt:
    name: ["wireguard", "resolvconf"]
    state: present
    update_cache: yes

- name: set /etc/network/interfaces
  template:
    src: templates/interfaces
    dest: /etc/network/interfaces

- name: set /etc/wireguard/wg0.conf
  template:
    src: templates/wg0.conf
    dest: /etc/wireguard/wg0.conf

- name: ensure wireguard service started
  service:
    name: wg-quick@wg0
    state: started
    enabled: true

- name: allow wireguard udp port
  ufw:
    rule: allow
    proto: udp
    port: "{{ wg0_port }}"

- sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

- sysctl:
    name: net.ipv6.conf.all.forwarding
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
