- hosts: thinkpad
  user: root
  become: yes
  connection: local
  roles:
    - bash
    - gpg-ssh-agent
    - ssh_config
    - git
    - mutt
    - tmux
    - libvirt/client/scripts
    - libvirt/client/certificates
    - nix/storage-box
    - nix/flakes
    - nix/wg-quick
    - nix/vim
    - thinkpad
