#!/bin/sh -e

echo "params: $@" 1>&2

if [ "$1" != "wg0" ]; then
  echo "$0: called with interface $1 not wg0, exiting" 1>&2
  exit 0;
fi

case "$2" in
    up|vpn-up)
    gateway=`ip route | grep default.*wlp58s0 | awk '{ print $3 }'`

    if [ -z "$gateway" ]; then
        echo "$0: no gateway found" 1>&2
        exit 0;
    fi

    echo "$0: adding route to {{ hostvars["vpn"].ipv4_address }} via $gateway dev $wlp58s0" 1>&2
    #ip route add {{ hostvars["vpn"].ipv4_address }}  via $IP4_GATEWAY dev $DEVICE_IFACE
    ;;
    down|vpn-down)
    echo "$0: deleting route to {{ hostvars["vpn"].ipv4_address }} via $IP4_GATEWAY dev $DEVICE_IFACE" 1>&2
    ip route del {{ hostvars["vpn"].ipv4_address }} dev $DEVICE_IFACE
    ;;
    *)
    echo "$0: called with unknown action \`$2'" 1>&2
    exit 0
    ;;
esac
