- name: copy nix configration files
  template:
    src: "{{ item }}"
    dest: "/etc/nixos/{{ item }}"
    mode: "644"
    owner: root
    group: root
  become: true
  notify: rebuild nix
  loop:
    - flake.nix
    - configuration.nix
