---
- name: restart haproxy
  service: 
    name: haproxy
    state: restarted

- name: reload haproxy
  service: 
    name: haproxy
    state: reloaded

- name: restart nginx
  service: 
    name: nginx
    state: restarted

- name: reload nginx
  service: 
    name: nginx
    state: reloaded

- name: restart postgres
  service: 
    name: postgresql
    state: restarted

- name: reload postgres
  service: 
    name: postgresql
    state: reloaded

- name: restart supervisor
  service: 
    name: supervisor
    state: restarted
