- name: Install packages
  apt:
    name: [
      'certbot',
      'python-certbot-nginx',
      'python-virtualenv',
      'git',
      'nginx',
    ]
    state: present
    update_cache: yes

- name: Get initial letsencypt SSL certificat
  shell: "systemctl stop nginx && certbot certonly --non-interactive --standalone -d tarnbarford.net --email tarn@tarnbarford.net --agree-tos && systemctl start nginx"
  args:
    creates: "/etc/letsencrypt/live/tarnbarford.net/cert.pem"

- name: Add website user group
  group:
    name: website
    state: present

- name: Add website user
  user:
    name: website
    shell: /bin/bash
    group: website

- name: Create website user
  postgresql_user:
     db: website
     user: website
     password: password
  become: yes
  become_user: postgres

- name: Clone website generator
  git:
    repo: https://github.com/tarnacious/website.git
    dest: /home/website/generator
    version: main
    accept_hostkey: True
    force: yes
  become: yes
  become_user: website

- name: Clone posts repository
  git:
    repo: https://github.com/tarnacious/posts.git
    dest: /home/website/generator/posts
    version: master
    accept_hostkey: True
    force: yes
  become: yes
  become_user: website

- name: Install python environment
  shell: python3 -m venv ./venv
  become: yes
  become_user: website
  args:
    chdir: /home/website/generator
    creates: /home/website/generator/venv

- name: Install python packages
  shell: ./venv/bin/pip install -r requirements.txt
  become: yes
  become_user: website
  args:
    chdir: /home/website/generator

- name: Generate site
  shell: ./venv/bin/python src/generate.py
  become: yes
  become_user: website
  args:
    chdir: /home/website/generator

- name: Configure nginx
  copy:
    src: templates/nginx.conf
    dest: /etc/nginx/sites-enabled/default
    owner: root
    group: root
  notify: restart nginx
