- name: Install package
  apt:
    name: 'tmux'

- name: Tmux configuration
  template:
    src: templates/tmux.conf
    dest: /home/{{ username }}/.tmux.conf
  become: yes
  become_user: "{{ username }}"
