- name: Install package
  apt:
    name: 'tmux'
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Tmux configuration
  template:
    src: templates/tmux.conf
    dest: /home/{{ username }}/.tmux.conf
  become: yes
  become_user: "{{ username }}"
