#!/usr/bin/env python

# Encrypt a single yaml variable fragment with ansible-vault.

from ansible.parsing.dataloader import DataLoader
from ansible.parsing.vault import ScriptVaultSecret
from ansible.parsing.vault import VaultLib
import sys
import os
import yaml

password_script_path = os.getcwd() + '/scripts/password'
secret = ScriptVaultSecret(password_script_path, loader=DataLoader())
secret.load()

vault = VaultLib([('default', secret)])

text = ''.join(sys.stdin.readlines())
data = yaml.load(text, Loader=yaml.SafeLoader)

def encrypt_yaml_value(value):
  encrypted_value = vault.encrypt(value)
  return encrypted_value.decode('utf-8')

items = list(data.items())
updated_items = list(map(lambda x: (x[0], encrypt_yaml_value(x[1])), items))

for x, y in updated_items:
    keys = '\n'.join(list(map(lambda x: f'  {x}', y.split('\n'))))
    print(f'{x}: !vault |\n{keys}')
