#!/usr/bin/env python

# Decrypt a single yaml variable fragment with ansible-vault.

from ansible.parsing.dataloader import DataLoader
from ansible.parsing.vault import ScriptVaultSecret
from ansible.parsing.vault import VaultLib
import sys
import os
import yaml

password_script_path = os.getcwd() + '/scripts/password'
secret = ScriptVaultSecret(password_script_path, loader=DataLoader())
secret.load()

vault = VaultLib([('default', secret)])

text = ''.join(sys.stdin.readlines())
data = text.split(': ')
key = data[0]
value = ''.join(data[1:])

def is_vault_secret(value):
    return value.startswith('!vault |')

def strip_vault_secret(value):
    lines = value.split('\n')[1:]
    return '\n'.join(map(lambda line: line.lstrip(' '), lines))

if not is_vault_secret(value):
        print("Not a vault secret")
        exit

cipher_text = strip_vault_secret(value)

plain_text = vault.decrypt(cipher_text).decode('utf-8')

print(f'{key}: "{plain_text}"')
