- name: Install list of packages
  apt:
    name: "perl-modules-5.28"
    state: present
    update_cache: yes

- name: Copy icinga client plugins
  copy:
    src: "{{ item }}"
    dest: "/{{ item }}"
    mode: "a+x"
  with_items:
    - usr/lib/nagios/plugins/check_mem.pl
    - usr/lib/nagios/plugins/check_raid.pl

