- name: Clone repository
  git:
    repo: "{{ repo }}"
    dest: /home/debugproxy/debugproxy
    version: "{{ branch }}"
    accept_hostkey: True
    force: yes
  become: yes
  become_user: debugproxy

- name: Copy settings.py
  template:
    src: templates/debugproxy/settings.py.j2
    dest: /home/debugproxy/debugproxy/config/default_settings.py

- name: Copy logging.ini
  copy:
    src: templates/debugproxy/logging.ini
    dest: /home/debugproxy/debugproxy/config/logging.ini

- name: Add logging dir
  file:
    path: /var/log/debugproxy
    state: directory
    owner: debugproxy
    group: debugproxy

- name: Install python environment
  shell: /opt/Python-3.7.17/python -m venv /home/debugproxy/debugproxy
  become: yes
  become_user: debugproxy

- name: Install wheel package
  shell: ./bin/pip install wheel
  args:
    chdir: /home/debugproxy/debugproxy/
  become: yes
  become_user: debugproxy

- name: Install setuptools package
  shell: ./bin/pip install -U setuptools
  args:
    chdir: /home/debugproxy/debugproxy/
  become: yes
  become_user: debugproxy

- name: Install python packages
  shell: ./bin/pip install -r requirements.txt
  args:
    chdir: /home/debugproxy/debugproxy/
  become: yes
  become_user: debugproxy

- name: Run setup.py
  shell: ./bin/python setup.py develop
  args:
    chdir: /home/debugproxy/debugproxy/
  become: yes
  become_user: debugproxy

- name: init database
  shell: ./bin/python manage.py init_db
  args:
    chdir: /home/debugproxy/debugproxy/
  become: yes
  become_user: debugproxy

# we need to use node 10 here, on the server it's currently installed with nvm
#- name: npm intall
#  shell: npm install
#  args:
#    chdir: /home/debugproxy/debugproxy/proxyui
#  become: yes
#  become_user: debugproxy
#
#- name: npm dist
#  shell: npm run dist
#  args:
#    chdir: /home/debugproxy/debugproxy/proxyui
#  become: yes
#  become_user: debugproxy

- name: Create /etc/cron.d/debugproxy_cron
  template:
    src: templates/cron/debugproxy_cron
    dest: /etc/cron.d/debugproxy_cron

- name: Create /home/debugproxy/.mitmproxy config directory
  file:
    path: /home/debugproxy/.mitmproxy
    state: directory
    owner: debugproxy
    group: debugproxy

- name: Copy proxy certificates
  copy:
    src: templates/certificates/{{ item.name }}
    dest: /home/debugproxy/.mitmproxy/{{ item.name }}
    owner: debugproxy
    group: debugproxy
  with_items:
    - { name: "mitmproxy-ca-cert.cer" }
    - { name: "mitmproxy-ca-cert.p12" }
    - { name: "mitmproxy-ca-cert.pem" }
    - { name: "mitmproxy-ca.pem" }
    - { name: "mitmproxy-dhparam.pem" }
