- name: create debugproxy database
  postgresql_db:
    name: debugproxy
  become: yes
  become_user: postgres

- name: create debugproxy user
  postgresql_user:
    db: debugproxy
    user: debugproxy
    password: "{{ debugproxy_postgres_password }}"
    encrypted: yes
  become: yes
  become_user: postgres

- name: grant permissions to debugproxy user
  postgresql_privs:
    db: debugproxy
    privs: ALL
    type: schema
    objs: public
    role: debugproxy
  become: yes
  become_user: postgres
