- name: Install packages
  apt:
    name: [
      'git',
      'python3',
      'python3-pip',
      'python3-venv'
    ]

- name: Ensure ~/projects
  file:
    path: /home/{{ username }}/projects
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Clone mojoreads-ansible project
  git:
    repo: "git@github.com:brainsome-de/mojoreads-ansible.git"
    dest: "/home/tarn/projects/mojoreads-ansible"
    version: "master"
    accept_hostkey: True
    force: no
    update: no
  become: yes
  become_user: "{{ username }}"

- name: Install mojoreads ansible virtual environment
  shell: python3 -m venv .
  become: yes
  become_user: "{{ username }}"
  args:
    chdir: "/home/{{ username }}/projects/mojoreads-ansible"

- name: Install mojoreads ansible virtual requirements
  shell: ./bin/pip install -r requirements.txt
  become: yes
  become_user: "{{ username }}"
  args:
    chdir: "/home/{{ username }}/projects/mojoreads-ansible"

- name: Install password file
  template:
    src: "templates/password"
    dest: /home/{{ username }}/projects/mojoreads-ansible/scripts/password
    mode: 0600
