- name: Install packages
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg2', 'software-properties-common']
    state: present
    update_cache: yes

- apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian buster stable
    state: present

- name: Install docker
  apt:
    name: ['docker-ce', 'docker-compose']
    state: present
    update_cache: yes

- name: Adding user to docker group
  user:
    name: "{{ username }}"
    groups: docker
    append: yes
