- hosts: debugproxy
  user: root
  become: yes
  roles:
    - vm-networking
    - hostname
    - firewall
    - certificates
    - backup-client
    - munin-node
    - icinga-client
    - icinga-plugins
    - debugproxy
