- hosts: hypervisor
  user: root
  become: yes
  roles:
    - hostname
    - sshd
    - certificates
    - munin-node
    - icinga-client
    - icinga-plugins
    - libvirt/server/packages
    - libvirt/server/scripts
    - hypervisor
