- hosts: icinga
  user: root
  become: yes
  roles:
    - vm-networking
    - hostname
    - apt
    - unattended-upgrades
    - sshd
    - firewall
    - sendmail
    - icinga
    - certificates
    - munin-node
    - icinga-plugins
    - letsencrypt-apache
