- hosts: load-balancer
  user: root
  become: yes
  roles:
    - vm-networking
    - sshd
    - hostname
    - apt
    - firewall
    - haproxy
    - certificates
    - munin-node
    - icinga-client
