- hosts: ns2
  user: root
  become: yes
  roles:
    - python
    - hostname
    - users
    - unattended-upgrades
    - sshd
    - firewall
    - certificates
    - icinga-client
    - icinga-plugins
    - munin-node
    - bind
