- hosts: tarnbarford
  user: root
  become: yes
  roles:
    - vm-networking
    - apt
    - hostname
    - sshd
    - certificates
    - backup-client
    - letsencrypt-nginx
    - munin-node
    - tarnbarford-website
    - icinga-client
