- hosts: thinkpad
  user: root
  become: yes
  connection: local
  roles:
    - bash
    - gpg-ssh-agent
    - libvirt/client/scripts
    - ssh_config
    - git
    - mutt
    - tmux
    - nix-wg-quick
    - thinkpad
