- name: ensure packages
  apt:
    name: [
      'bind9',
      'bind9utils',
      'bind9-doc'
    ]
    state: present
    update_cache: yes

- name: ensure zones directory
  file:
    path: /etc/bind/zones
    state: directory

- name: ensure configuration
  template:
    src: "templates{{ item }}"
    dest: "{{ item }}"
  with_items:
    - '/etc/bind/named.conf'
    - '/etc/bind/named.conf.options'
    - '/etc/bind/named.conf.local'
    - '/etc/bind/zones/db.tarnbarford.net'
    - '/etc/bind/zones/db.internal.tarnbarford.net'
    - '/etc/bind/zones/db.debugproxy.com'
  notify: restart bind

- name: check config
  command: 'named-checkzone tarnbarford.net /etc/bind/zones/db.tarnbarford.net'
  register: out

- debug: msg="{{ out.stdout_lines }}"

- name: check config
  command: 'named-checkzone internal.tarnbarford.net /etc/bind/zones/db.internal.tarnbarford.net'
  register: out

- debug: msg="{{ out.stdout_lines }}"

- name: check config
  command: 'named-checkzone debugproxy.com /etc/bind/zones/db.debugproxy.com'
  register: out

- debug: msg="{{ out.stdout_lines }}"

- name: Allow bind dns port in UFW
  ufw:
    rule: allow
    port: '53'

- name: Allow bind remote name daemon control port in UFW
  ufw:
    rule: allow
    port: '953'

- name: Link bind munin modules
  file:
    src: '/usr/share/munin/plugins/{{ item.src }}'
    dest: '/etc/munin/plugins/{{ item.dest }}'
    state: link
  with_items:
    - { src: 'bind9_rndc', dest: 'bind9_rndc' }
    - { src: 'bind9', dest: 'bind9' }
