- name: create certificate directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /etc/pki/CA/
    - /etc/pki/libvirt/
    - /etc/pki/libvirt/private/
    - /etc/pki/libvirt-vnc/

- name: copy libvirtd ca certificate
  copy:
    src: ../../ca/ca.crt
    dest: /etc/pki/CA/cacert.pem
  notify: restart libvirtd

- name: copy libvirtd private key
  copy:
    src: ../../ca/server.key
    dest: /etc/pki/libvirt/private/serverkey.pem
    mode: "600"
    owner: root
    group: root
  notify: restart libvirtd

- name: copy libvirtd public key
  copy:
    src: ../../ca/server.crt
    dest: /etc/pki/libvirt/servercert.pem
  notify: restart libvirtd

- name: copy libvirt qemu configuration
  copy:
    src: templates/qemu.conf
    dest: /etc/libvirt/qemu.conf
  notify: restart libvirtd

- name: copy libvirt-vnc ca certificate
  copy:
    src: ../../ca/ca.crt
    dest: /etc/pki/libvirt-vnc/ca-cert.pem
  notify: restart libvirtd

- name: copy libvirt-vnc private key
  copy:
    src: ../../ca/server.key
    dest: /etc/pki/libvirt-vnc/server-key.pem
  notify: restart libvirtd

- name: copy libvirt-vnc public key
  copy:
    src: ../../ca/server.crt
    dest: /etc/pki/libvirt-vnc/server-cert.pem
  notify: restart libvirtd
