#!/usr/bin/env bash

if [ "$#" -ne 2 ]; then
    echo "Usage: attch-device <domain> ~/devices/<device file>"
    exit 1
fi

virsh detach-device $1 $2 && true
sleep 1
virsh attach-device $1 $2 && true
sleep 1
virsh detach-device $1 $2 && true
sleep 1
virsh attach-device $1 $2 && true
