---
- name: Create workspace directory
  ansible.builtin.file:
    path: "{{ tarnbarford_workspace_path }}"
    state: directory
    owner: tarn
    group: tarn
    mode: '0755'

- name: nix flake configuration
  ansible.builtin.template:
    src: templates/{{ item }}
    dest: "{{ tarnbarford_workspace_path }}/"
    owner: tarn
    group: tarn
    mode: '0644'
  loop:
    - flake.nix
    - guest.nix
    - configuration.nix

- name: Build and deploy scripts
  ansible.builtin.template:
    src: "templates/{{ item }}"
    dest: "{{ tarnbarford_workspace_path }}/{{ item }}"
    owner: tarn
    group: tarn
    mode: '0755'
  loop:
    - build-and-deploy

- name: Install hypervisor instructions README
  ansible.builtin.template:
    src: "templates/README.md"
    dest: "{{ tarnbarford_workspace_path }}/README.md"
    owner: tarn
    group: tarn
    mode: '0644'

- name: Define VM
  community.libvirt.virt:
    command: define
    name: "{{ tarnbarford_vm_name }}"
    xml: "{{ lookup('template', 'templates/domain.xml') }}"

#- name: Start ownCloud VM
#  community.libvirt.virt:
#    command: start
#    name: "ocis"
#    state: running
