export PATH=$PATH:$HOME/bin
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export EDITOR=vim
export HISTCONTROL=ignoredups

PS1="${debian_chroot:+($debian_chroot)}\[\033[01;36m\]\u@\h\[\033[00m\]:\[\033[01;32m\]\w\[\033[00m\]\[\033[01;31m\]\\[\033[00m\]$ "

[ -f $HOME/.bashrc ] && . $HOME/.bashrc

profiles=$(shopt -s nullglob dotglob; echo $HOME/.profiles/*)
for f in $profiles; do
   . $f
done
