- name: Install ca-certificates
  apt:
    name: [
      "ca-certificates",
      "apt-transport-https"
    ]
    state: present

      #- apt_key:
      #    url: https://download.owncloud.org/download/repositories/10.7.0/Debian_10/Release.key
      #    state: present
      #
      #- apt_repository:
      #    repo: deb https://download.owncloud.org/download/repositories/10.7.0/Debian_10/ /
      #    state: present

- name: Install list of packages
  apt:
    name: [
      "curl",
      "apt-transport-https",
      "apache2",
      "mariadb-server",
      "libapache2-mod-php7.4",
      "openssl",
      "php-imagick",
      "php7.4-common",
      "php7.4-curl",
      "php7.4-gd",
      "php7.4-mbstring",
      "php7.4-imap",
      "php7.4-intl",
      "php7.4-json",
      "php7.4-mbstring",
      "php7.4-mysql",
      "php7.4-xml",
      "php7.4-zip",
      "php7.4-apcu",
      "php7.4-redis",
      "redis-server",
      #"python-mysqldb",
      "certbot",
      "python-certbot-apache",
      "exif",
      "libav-tools",
      "libreoffice"
    ]
    state: present
    update_cache: yes

- name: Install list of packages
  apt:
    name: owncloud-complete-files
    state: present
    update_cache: yes

- name: mariadb config
  template:
    src: templates/50-server.cnf
    dest: /etc/mysql/mariadb.conf.d/50-server.cnf
  notify: restart mariadb

    #- name: Ensure owncloud database
    #  mysql_db:
    #    name: owncloud
    #    state: present
    #
    #- name: Ensure owncloud database user
    #  mysql_user:
    #    name: owncloud
    #    password: "{{ owncloud_db_password }}"
    #    priv: 'owncloud.*:ALL'
    #    state: present

- name: Apache default website config
  template:
    src: templates/default
    dest: /etc/apache2/sites-enabled/000-default.conf
  notify: restart apache2

- name: Apache default-ssl website config
  template:
    src: templates/default-ssl
    dest: /etc/apache2/sites-enabled/default-ssl.conf
  notify: restart apache2

- name: Apache owncloud website config
  template:
    src: templates/owncloud
    dest: /etc/apache2/sites-enabled/owncloud.conf
  notify: restart apache2

- name: Enable apache modules
  apache2_module:
    name: "{{item}}"
    state: present
  with_items:
    - rewrite
    - headers
    - env
    - dir
    - mime
    - ssl
  notify: restart apache2

- name: add external apps
  file:
    dest: /var/www/owncloud/apps-external
    owner: www-data
    group: www-data
    mode: u=rwX,g=rX,o=rX
    state: directory

- name: owncloud config
  template:
    src: templates/config.php
    dest:  /var/www/owncloud/config/config.php
  notify: restart apache2

- name: Allow web ports through firewall
  ufw:
    rule: allow
    port: '{{ item }}'
    proto: tcp
  with_items:
    - '80'
    - '443'
