- name: Install ca-certificates
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  with_items:
    - ca-certificates
    - apt-transport-https

- apt_key:
    url: https://download.owncloud.org/download/repositories/stable/Debian_10/Release.key
    state: present

- apt_repository:
    repo: deb https://download.owncloud.org/download/repositories/stable/Debian_10/ /
    state: present

- name: Install list of packages
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  with_items:
    - curl
    - apt-transport-https
    - apache2
    - mariadb-server
    - libapache2-mod-php7.0
    - openssl
    - php-imagick
    - php7.3-common
    - php7.3-curl
    - php7.3-gd
    - php7.3-mbstring
    - php7.3-imap
    - php7.3-intl
    - php7.3-json
      #- php7.0-ldap
    - php7.3-mbstring
      #- php7.3-mcrypt
    - php7.3-mysql
      #- php7.0-pgsql
      #- php-smbclient
      #- php-ssh2
      #- php7.0-sqlite3
    - php7.3-xml
    - php7.3-zip
    - php7.3-apcu
    - php7.3-redis
    - redis-server
    # ansible
    - python-mysqldb
    # certbot
    - certbot
    - python-certbot-apache
    - exif
    - libav-tools
    - libreoffice

- name: Install list of packages
  apt:
    name: owncloud-files
    state: present
    update_cache: yes

- name: mariadb config
  template:
    src: templates/50-server.cnf
    dest: /etc/mysql/mariadb.conf.d/50-server.cnf
  notify: restart mariadb

- name: Ensure owncloud database
  mysql_db:
    name: owncloud
    state: present

- name: Ensure owncloud database user
  mysql_user:
    name: owncloud
    password: "{{ owncloud_db_password }}"
    priv: 'owncloud.*:ALL'
    state: present

- name: Apache default website config
  template:
    src: templates/default
    dest: /etc/apache2/sites-enabled/000-default.conf
  notify: restart apache2

- name: Apache default-ssl website config
  template:
    src: templates/default-ssl
    dest: /etc/apache2/sites-enabled/default-ssl.conf
  notify: restart apache2

- name: Apache owncloud website config
  template:
    src: templates/owncloud
    dest: /etc/apache2/sites-enabled/owncloud.conf
  notify: restart apache2

- name: Enable apache modules
  apache2_module:
    name: "{{item}}"
    state: present
  with_items:
    - rewrite
    - headers
    - env
    - dir
    - mime
    - ssl
  notify: restart apache2

- name: add external apps
  file:
    dest: /var/www/owncloud/apps-external
    owner: www-data
    group: www-data
    mode: u=rwX,g=rX,o=rX
    state: directory

- name: owncloud config
  template:
    src: templates/config.php
    dest:  /var/www/owncloud/config/config.php
  notify: restart apache2
