- name: add sshd_config
  copy:
    src: templates/sshd_config
    dest: /etc/ssh/sshd_config
  notify: reload sshd

- name: Creates directory
  file:
    path: "/home/tarn/.ssh"
    state: directory
    mode: 0700

- name: ensure authorized_key
  template:
    src: "templates/authorized_keys"
    dest: "/home/tarn/.ssh/authorized_keys"
    owner: tarn
    group: tarn
    mode: 0644
